version: '3'
services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: '${CONTAINER_NAME}'
        restart: unless-stopped
        ports:
            - '${CONTAINER_PORT}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - logi
networks:
    logi:
        external: true
